### ISSUE TITLE
Not enough contrast in icons in Dark mode

### ISSUE THREAD

**Issue by MikelLuri** [txiribimakula/neo-watch#34]
The icons for "view" and "refresh" have very low contrast in Dark mode
![image](https://github.com/txiribimakula/neo-watch/assets/6429313/1fb20e43-4e5b-4c2e-b1d4-05beef852679)

**Comment by txiribimakula** [comment]
Should be fixed when [v0.3.16](https://github.com/txiribimakula/neo-watch/releases/tag/v0.3.16) is released.

![image](https://github.com/txiribimakula/neo-watch/assets/33623535/aa271ef3-c0b6-4f24-97eb-1bf333986866)
![image](https://github.com/txiribimakula/neo-watch/assets/33623535/23a3c196-a2b8-47b2-9a8b-2ba69be74f1f)
